# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('tagtime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Pixlee', max_length=30)),
            ],
        ),
    ]
